sudo: required
services:
 - docker
language: python
python:
 - 2.7

matrix:
  exclude:
    - python: 3.5
  include:
    - python: 2.7
      env: RUN_LINTS=true
cache: pip

before_install: bash -xe travis/before-install.sh
install: pip install -r requirements-dev.txt
script: bash -xe travis/test-script.sh

notifications:
  email:
    - dmlb2000@gmail.com
    - derek.hopkins@pnnl.gov
